### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by Turab** [Dansoftowner/Boomega#162]
I would like to translate Boomega to Turkish. How can I?

**Comment by Dansoftowner** [comment]
Hi!

Thanks for your devotion!

You can create your own resource file accordingly to [this](https://github.com/Dansoftowner/Boomega/blob/dev/src/main/resources/com/dansoftware/boomega/i18n/Values.properties). You can simply send it to me OR create your own pull request, in that case please follow the guidelines below:
- Work in the `dev` branch
- Place your resource file here: `src/main/resources/com/dansoftware/boomega/i18n` and name it `Values_tr_TR.properties`
- Create a `LanguagePack` implementation (e.g `TurkishLanguagePack`), take a look at the [EnglishLanguagePack](https://github.com/Dansoftowner/Boomega/blob/dev/src/main/java/com/dansoftware/boomega/i18n/EnglishLanguagePack.java) and the [HungarianLanguagePack](https://github.com/Dansoftowner/Boomega/blob/dev/src/main/java/com/dansoftware/boomega/i18n/HungarianLanguagePack.java) to have an idea how you can do it
- Register your language-pack [here](https://github.com/Dansoftowner/Boomega/blob/dev/src/main/java/com/dansoftware/boomega/i18n/I18N.java#L118)

Note that the app is still in a very early stage, so your translation might get deprecated by the time, but it shouldn't hold you back 
to do it, in fact I would be really thankful for your contribution!

If you have any more questions, feel free to contact me!

Best regards

**Comment by Turab** [comment]
Thank you for the guidelines. I created the pull request.

**Comment by Dansoftowner** [comment]
Thank you!
